In [1]:
import pandas as pd
import math as m
import numpy as np
import scipy as sp
import matplotlib as plt
import matplotlib.pyplot as plt
import seaborn as sns 
import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn.linear_model import LinearRegression
from sklearn import tree
from sklearn.datasets import load_iris
import random as rnd
%matplotlib inline
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import preprocessing
from sklearn import utils

In [2]:
train = pd.read_excel('PPR Fantasy WR Training Data.xlsx', encoding = "iso-8859-1")
test = pd.read_excel('2020-2021 Rookie Fantasy WR Testing Data.xlsx', encoding = "iso-8859-1")
test.head()

,GP,TGT,REC,YDS,YDS/G,AVG,TD,ATT,YDS.1,AVG.1,TD.1,FL,FPTS,FPPG,Result (PPG)
0,13,0,62,1327,102.076923,21.403226,14,0,0,0,0,0,0,0,NaN
1,13,0,77,1163,89.461538,15.103896,10,0,0,0,0,0,0,0,NaN
2,12,0,43,611,50.916667,14.209302,5,0,0,0,0,0,0,0,NaN
3,15,0,111,1540,102.666667,13.873874,18,0,0,0,0,0,0,0,NaN
4,12,0,40,746,62.166667,18.650000,7,0,0,0,0,0,0,0,NaN

In [3]:
#X_train = train.drop("Result", axis=1)
#Y_train = train["Result"]
#X_train.shape, Y_train.shape, test.shape

y = train["Result (PPG)"]
features = [" GP", " REC", " YDS", " YDS/G", " AVG", " TD"]
X = pd.get_dummies(train[features])
X_test = pd.get_dummies(test[features])

In [8]:
random_forest = RandomForestClassifier(n_estimators=100)

random_forest.fit(X, y)

Y_pred = random_forest.predict(X_test)
print(Y_pred)

[18 13 13 18 10 18 15 13 13 16]